### PR TITLE
Tear down error handler

### LINKED ISSUE #25: warning: possible EventEmitter memory leak detected
I periodically encounter this warning, either when running the publish-relation example (haven't tried the react todos), or from run-tests.sh  

I'm not certain that this is truly bad but one time I got it, it was accompanied by a pretty major delay in talking to the database.

I'd like to track the problem down but I'm still beginning with meteor.  I'd be grateful for any clues.

Here is the log.

```
W20150923-12:25:46.222(-7)? (STDERR) (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
W20150923-12:25:46.239(-7)? (STDERR) Trace
W20150923-12:25:46.240(-7)? (STDERR)     at PgLiveQuery.addListener (events.js:160:15)
W20150923-12:25:46.240(-7)? (STDERR)     at [object Object].PG.Query.observe (pg.js:30:10)
W20150923-12:25:46.240(-7)? (STDERR)     at [object Object].accounts._server.publish.is_auto [as _handler] (packages/accounts-base/accounts_server.js:703:1)
W20150923-12:25:46.240(-7)? (STDERR)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1675:1)
W20150923-12:25:46.240(-7)? (STDERR)     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1006:1)
W20150923-12:25:46.240(-7)? (STDERR)     at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:825:1)
W20150923-12:25:46.240(-7)? (STDERR)     at packages/ddp-server/livedata_server.js:407:1
W20150923-12:25:46.241(-7)? (STDERR)     at Array.forEach (native)
W20150923-12:25:46.241(-7)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
W20150923-12:25:46.241(-7)? (STDERR)     at [object Object]._.extend.startUniversalSubs (packages/ddp-server/livedata_server.js:406:1)
W20150923-12:25:46.241(-7)? (STDERR)     at [object Object]._.extend._setUserId (packages/ddp-server/livedata_server.js:800:1)
W20150923-12:25:46.242(-7)? (STDERR)     at [object Object].setUserId [as _setUserId] (packages/ddp-server/livedata_server.js:666:1)
W20150923-12:25:46.242(-7)? (STDERR)     at [object Object]._.extend.setUserId (packages/ddp-common/method_invocation.js:94:1)
W20150923-12:25:46.242(-7)? (STDERR)     at AccountsServer.Ap._loginUser (packages/accounts-base/accounts_server.js:269:1)
W20150923-12:25:46.242(-7)? (STDERR)     at AccountsServer.Ap._attemptLogin (packages/accounts-base/accounts_server.js:323:1)
W20150923-12:25:46.243(-7)? (STDERR)     at [object Object].methods.login (packages/accounts-base/accounts_server.js:498:1)
W20150923-12:25:46.244(-7)? (STDERR)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1675:1)
W20150923-12:25:46.244(-7)? (STDERR)     at packages/ddp-server/livedata_server.js:704:1
W20150923-12:25:46.244(-7)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
W20150923-12:25:46.244(-7)? (STDERR)     at packages/ddp-server/livedata_server.js:703:1
W20150923-12:25:46.244(-7)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
W20150923-12:25:46.244(-7)? (STDERR)     at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:702:1)
```

### PR DESCRIPTION
**Pull request by rclai**
Fixes #25.

### CODE REVIEW

**Comment by stubailo** [comment]
Hmm, I think I'd need @Slava to take a look at this.

**Comment by rclai** [comment]
Yeah, I wasn't sure where to do it, so I did it where the other callback was being torn down.

**Comment by Slava** [comment]
I wouldn't be able to look at this in the near future. Let me know if you
need more comments on the code to get this fixed.

**Comment by rclai** [comment]
The error event listener was not being removed when the query was stopped and therefore it was giving a "Warning, possible memory leak detected" when subsequent queries were being made. In addition, the [stack trace](https://github.com/meteor/postgres-packages/issues/25#issue-107992122) of that warning led me to [this line of code](https://github.com/meteor/postgres-packages/blob/master/packages/pg/pg.js#L30). So I moved the error listener to be under the hood. Since you created [this clean-up method](https://github.com/rclai/postgres-packages/blob/d7cd7e0224fa4e0105685953552fc49d56be25fb/packages/pg/observe-driver/polling-driver.js#L197), I figured that's the ideal place to tear down the error listener. Let me know if that doesn't make sense.

**Comment by stubailo** [comment]
LGTM

**Comment by Slava** [comment]
:+1:

**Pull request merged**
