### PR TITLE
Add example to loop through a cursor from knex

### PR DESCRIPTION
**Pull request by yoonghm**

### CODE REVIEW

**Comment by Slava** [comment]
Is this example really necessary? Do developers not know how to iterate over an array? Especially given that this is not the best way anyway.

**Comment by stubailo** [comment]
Yeah, I'm inclined to agree. It's just a JavaScript array, no?

**Comment by yoonghm** [comment]
I am very new to javascript, and meteor too. I am trying reading a lot of documents to figure out how to use meteor with postgresql. The problem meteor changes everyday, ...

**Comment by stubailo** [comment]
Yeah, I think we assume pretty good knowledge of JavaScript in this guide, sorry about that.

If you're a beginner Meteor/JS user, I don't think using Meteor with PostgreSQL is ideal - it's a pretty experimental package with a lot of rough edges.

**Comment by rclai** [comment]
I would stay away from the `for x in object` kind of loop and use the native `array.forEach()`.

**Pull request closed without merging**
